kube-prometheus-stack:
  grafana:
    admin:
      existingSecret: grafana-admin
      userKey: admin-user
      passwordKey: admin-password

    persistence:
      enabled: true
      type: pvc
      accessModes:
        - ReadWriteOnce
      size: 5Gi

    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
          - name: Loki
            type: loki
            access: proxy
            url: http://loki-gateway.monitoring.svc.cluster.local
            isDefault: false

  prometheus:
    prometheusSpec:
      retention: 7d

  additionalPrometheusRulesMap:
    custom-alerts:
      groups:
        - name: custom.rules
          rules:
            - alert: ProductionHighCPUUsage
              expr: |
                sum(rate(container_cpu_usage_seconds_total{namespace="production"}[5m]))
                /
                sum(machine_cpu_cores)
                * 100 > 80
              for: 2m
              labels:
                severity: warning
              annotations:
                summary: "Production High CPU usage"

            - alert: ProductionHighMemoryUsage
              expr: |
                sum(container_memory_usage_bytes{namespace="production"}) 
                / sum(machine_memory_bytes) 
                * 100 > 80
              for: 2m
              labels:
                severity: warning
              annotations:
                summary: "Production High CPU Usage"

            - alert: DevelopmentHighCPUUsage
              expr: |
                sum(rate(container_cpu_usage_seconds_total{namespace="development"}[5m]))
                /
                sum(machine_cpu_cores)
                * 100 > 80
              for: 2m
              labels:
                severity: warning
              annotations:
                summary: "Development High CPU Usage"

            - alert: DevelopmentHighMemoryUsage
              expr: |
                sum(container_memory_usage_bytes{namespace="development"}) 
                / sum(machine_memory_bytes) 
                * 100 > 80
              for: 2m
              labels:
                severity: warning
              annotations:
                summary: "Development High Memory Usage"